### ISSUE TITLE
Feature request: Make ktx able to unset KUBECONFIG

### ISSUE THREAD

**Issue by scottslowe** [heptiolabs/ktx#15]
Like many other users, I use a prompt that displays the current Kubernetes context (and namespace, if specified). As such, it would be handy if `ktx` had the ability to unset the `KUBECONFIG` environment variable (and thus release space in my prompt). I have an idea on how to do this, but I wanted to check here to see if this was something the project owners might be interested in.

Thoughts?

**Comment by chuckha** [comment]
I think it's a great idea.

**Comment by scottslowe** [comment]
OK, I'll work on a PR.

**Comment by chuckha** [comment]
closed by #17

@scottslowe if you add "fixes #<issue number>" to the description of your PRs GitHub will auto-close the issues for you! It doesn't seem to recognize "addresses #<issue number>" :(
